name: Build Electron App and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Vite app
        run: npm run build
        env:
          VITE_ELECTRON: true
      - name: Build Electron app
        run: npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.os }}
          path: dist_electron/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist_electron/**
          body: |
            You can also try the web version of this app at:
            https://danielmeixner.github.io/sbomdepsviewer/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
