name: Build Electron App and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Vite app
        run: npm run build
        env:
          VITE_ELECTRON: true
      - name: Build Electron app (Linux)
        run: npx electron-builder --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-linux
          path: dist_electron/

  build-macos:
    runs-on: macos-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Vite app
        run: npm run build
        env:
          VITE_ELECTRON: true
      - name: Build Electron app (macOS)
        run: npx electron-builder --mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-macos
          path: dist_electron/

  build-windows:
    runs-on: windows-latest
    needs: build-macos
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Vite app
        run: npm run build
        env:
          VITE_ELECTRON: true
      - name: Build Electron app (Windows)
        run: npx electron-builder --win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-windows
          path: dist_electron/

  create-release:
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: electron-app-linux
          path: dist_electron/
      - uses: actions/download-artifact@v4
        with:
          name: electron-app-macos
          path: dist_electron/
      - uses: actions/download-artifact@v4
        with:
          name: electron-app-windows
          path: dist_electron/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist_electron/**
          body: |
            You can also try the web version of this app at:
            https://danielmeixner.github.io/SBOM-Dependency-Viewer/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
